name: send_data

on: [push] 

jobs:
  send_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files Again
        run: ls -a
